version: '3'
services:
  redis:
    image: redis:3

    ports:
      - "6379:6379"
    volumes:
      - ~/docker-volumes/redis:/var/lib/redis

  sorry:
    image: sorry
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /usr/share/fonts:/usr/share/fonts
    container_name: sorry
    environment:
      - PYTHONPATH:/home/code/sorrypy
    working_dir: /home/code/sorrypy
    depends_on:
      - redis